name: hallo_doctor_doctor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  google_sign_in: ^5.1.1
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.3
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.7
  flutter_svg: ^1.0.1
  get_storage: ^2.0.3
  table_calendar: ^3.0.3
  flutter_form_builder: 7.0.0
  form_builder_validators: ^7.2.0
  cached_network_image: ^3.2.0
  string_validator: ^0.3.0
  lottie: ^1.2.1
  rounded_loading_button: ^2.0.9
  date_count_down:
  flutter_rating_bar: ^4.0.0
  package_info_plus: ^1.3.0
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  firebase_storage: ^10.2.5
  firebase_database: ^9.0.6
  flutter_dotenv: ^5.0.2
  flutter_chat_ui:
    git: https://github.com/amsyary/flutter_chat_ui.git
  uuid: ^3.0.6
  file_picker: ^5.0.1
  mime: ^1.0.1
  flutter_firebase_chat_core:
    git: https://github.com/amsyary/flutter_firebase_chat_core.git
  jiffy: ^5.0.0
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.10
  dropdown_search: ^2.0.1
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  agora_rtc_engine: ^5.3.0
  permission_handler: ^9.2.0
  image_cropper: ^2.0.3
  flutter_exit_app: ^1.0.5
  intl_phone_field: ^3.1.0
  country_codes: ^2.2.0
  devicelocale: ^0.5.5

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
